- hosts: finalctf
  remote_user: root
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present
    - name: Git shellnoob
      git:
        repo: https://github.com/reyammer/shellnoob.git
        dest: ~/noob/
        accept_hostkey: yes
        force: yes
    - name: install pexpect
      pip:
        name: pexpect
        version: 3.3
    - name: install shellnoob
      shell: yes '' | /root/noob/shellnoob.py --install
    - name: install pwntools
      pip:
        name: pwntools